# Generated by Django 4.2.8 on 2023-12-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status_id",
            field=models.ForeignKey(
                default="open",
                on_delete=django.db.models.deletion.CASCADE,
                to="todolist.status",
            ),
        ),
    ]
